### DISCUSSION TITLE
My installation

### DISCUSSION THREAD

**Discussion by Jorge-Crespo-Celdran** [mansellrace/comelit-esphome#4] [Show and tell]
I just wanted to share my installation.

It was very easy, I had space to hide the device behind intercom and also it worked at first try. Zero issues. Thanks a lot to Francesco!.

**My ESPHome Yaml**

```
esphome:
  name: telefonillo

esp8266:
  board: d1_mini

wifi:
  ssid: "SSID"
  password: "PASS"
  power_save_mode: none
  reboot_timeout: 1min
  manual_ip:
    static_ip: 192.168.2.107
    gateway: 192.168.1.1
    subnet: 255.255.0.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

external_components:
  - source: github://mansellrace/comelit-esphome
  
comelit_intercom:

binary_sensor:
  - platform: comelit_intercom
    address: 6
button:
  - platform: template
    name: Open Door
    on_press:
      - comelit_intercom.send:
          command: 16
          address: 6
  - platform: template
    name: call intercom
    on_press: 
      - comelit_intercom.send:
          command: 32
          address: 6
  - platform: template
    name: screen on
    on_press: 
      - comelit_intercom.send:
          command: 20
          address: 6
```

**Installation images:**
![WhatsApp Image 2024-05-24 at 20 09 07 (2)](https://github.com/mansellrace/comelit-esphome/assets/86021690/12c1ea87-4389-4b30-b963-38148faaa27e)
![WhatsApp Image 2024-05-24 at 20 09 07 (1)](https://github.com/mansellrace/comelit-esphome/assets/86021690/bb2e5051-7c0a-48f2-949f-4e2344c60dd5)
![WhatsApp Image 2024-05-24 at 20 09 07](https://github.com/mansellrace/comelit-esphome/assets/86021690/aa2b9da6-4603-4e5e-b66c-2f18f0b1f36e)
![WhatsApp Image 2024-05-24 at 20 09 07 (3)](https://github.com/mansellrace/comelit-esphome/assets/86021690/cb9ae659-c933-4cf5-907b-94bb296ce52d)

**This is integrated in my HomeAssistant:**
![WhatsApp Image 2024-05-24 at 20 09 34](https://github.com/mansellrace/comelit-esphome/assets/86021690/1ff22d17-f317-40fa-950f-d307ea582703)

**Comment by stoeppke** [comment]
I'm in a ~35 party that needs 2 doors to be opened until you are in one of 2 possible hallways.

Each hallway has its own [1440 floor switch](https://pro.comelitgroup.com/product/1440).
Each door has its own [4681 audio/video unit](https://pro.comelitgroup.com/product/4681).

One door opens with command 16, the other with a combination of first sending 19, then ,5s later 16 (thanks @mansellrace for the help 😘) ([commd list see here](https://github.com/mansellrace/comelit-esphome/blob/main/protocol.md)).

The addresses are set by the apartment number, an up counting number.

My own apartment door has a KVF enabled door with a KNX bus adapter, so I can with this now finally open all 3 doors without any key.

My setup is not even 2h old and olready operational enough i would never need to touch it i guess.
Thanks for the already flashed delivered PCB with 8266 that was max convinient to commission @mansellrace .
I just missed a bit the "use this yaml" hint - i actually had to (not think anymore) - ask AI to generate me one 🥲 - and get hints per mail.

so here is my yaml:

```yaml
esphome:
  name: comelit
  friendly_name: comelit

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  homeassistant_services: true
  encryption:
    key: "XXX"

ota:
  - platform: esphome
    password: "XXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Comelit Fallback Hotspot"
    password: "XXX"

captive_portal:
    

external_components:
  - source: github://mansellrace/comelit-esphome

comelit_intercom:

binary_sensor:
  - platform: comelit_intercom
    name: Doorbell
    address: 5

button:
  - platform: template
    name: Open Door
    on_press:
      - comelit_intercom.send:
          command: 16
          address: 5
  - platform: template
    name: Open Building Door
    on_press:
      - comelit_intercom.send:
          command: 19
          address: 5
      - delay: 500ms
      - comelit_intercom.send:
          command: 16
          address: 5
```

Im trying to be "nice" and tell who opens the door (address 5) if someone (sparky) would try to debug the bus once.
Will probably never happen on this level.

And here some inspirational images of my setup and the building setup (the building setup is not exacly ideal - we can not say we dont have problems in our building - no video in higher floors, DSL for some breaks when the bell gose...)

![IMG_6007](https://github.com/user-attachments/assets/8c0281b8-77aa-4f46-b48e-f80e0a7c9487)
![IMG_6010](https://github.com/user-attachments/assets/b2bd58c3-fb2e-4500-8a25-63c6ac6faf26)
![IMG_6006](https://github.com/user-attachments/assets/01bfaef1-7b62-4164-bca8-f42c377877fa)
![IMG_0264_](https://github.com/user-attachments/assets/b865596c-4184-4ab2-ba56-d9f8bd094197)
![IMG_0265_](https://github.com/user-attachments/assets/d1e996ca-0ea7-4cbc-849f-6e2add065913)
![IMG_0266_](https://github.com/user-attachments/assets/7a16238f-6c3d-40a2-aa57-52f686d3948e)

Thanks again @mansellrace for the amazing project!
